### ISSUE TITLE
[Android] Reload JS will cause all previous navigated pages render

### ISSUE THREAD

**Issue by beast** [wix/react-native-navigation#108]
Hi, all. I asked this in a separate issue(https://github.com/wix/react-native-navigation/issues/74) but I think I better ask separately. 

This is easily reproducible in example-redux. Simply run the example with console tracing in all render functions:

Android - Navigate through few pages, then reload JS and you will see all previous navigated pages render function gets called.

iOS - Navigate through few pages, then reload JS and everything works just fine. Only the entry page render function is called.

I am suspecting this has to do with how Android and iOS reload JS bundle. My temp workaround now is to restart the app when debugging but obviously this is not a long term option. Maybe I shall ask this with React Native team but I guess I'll check with you guys first. Thanks.

**Comment by guyca** [comment]
@beast Thanks for reporting, It's a known issue. Hope to fix it this week

**Comment by webzepter** [comment]
Also bumped into this issue. Reload JS triggers screen mounting (iOS, Android both) -> it starts API requests -> at that time Redux store with API token is empty -> backend returns errors due missing token

**Comment by guyca** [comment]
@webzepter Are you sure this happens also on iOS? We've solved it a few weeks back, might be a regression.

**Comment by guyca** [comment]
@webzepter @beast Could you guys please checkout [this branch](https://github.com/wix/react-native-navigation/tree/bundleReload) and let me know if it solves the reload issue?

https://github.com/wix/react-native-navigation/tree/bundleReload

**Comment by guyca** [comment]
Should be fixed on Android in 7263e1b4cfc31a8079df0f984d236526d3c6b4ee

@webzepter Can you please confirm you're indeed seeing this issue on iOS as well? thanks.

**Comment by beast** [comment]
Hi, @guyca I was out sick for few days. I tried this today, it works on the very first reload but all subsequent reload still have the same issue. I am seeing below in logcat. : 
`07-05 02:13:41.210 14341-14341/com.livepay W/System.err:     at com.reactnativenavigation.core.RctManager$CustomDevCommandsHandler.onJSBundleReloaded(RctManager.java:191)
07-05 02:13:41.210 14341-14341/com.livepay W/System.err:     at com.reactnativenavigation.core.RctManager$CustomDevCommandsHandler.onJSBundleLoadedFromServer(RctManager.java:181)`

I am investigating what is going on maybe it has to do with the react views not being removed successfully? (https://github.com/wix/react-native-navigation/blob/7263e1b4cfc31a8079df0f984d236526d3c6b4ee/android/app/src/main/java/com/reactnativenavigation/activities/SingleScreenActivity.java)

**Comment by guyca** [comment]
@beast Can you please provider a more complete stack trace? thanks.

**Comment by beast** [comment]
Hi, @guyca . Sorry about the delay. Below are the full stack trace:
`07-11 01:59:44.994 16169-16169/com.livepay W/System.err: java.lang.NoSuchFieldException: No field mAttachScheduled in class Lcom/facebook/react/ReactRootView; (declaration of 'com.facebook.react.ReactRootView' appears in /data/app/com.livepay-1/base.apk)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.utils.ReflectionUtils.setField(ReflectionUtils.java:14)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.views.RctView.onRemoveFromScreen(RctView.java:78)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.views.ScreenStack.removeAllReactViews(ScreenStack.java:173)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.activities.SingleScreenActivity.removeAllReactViews(SingleScreenActivity.java:109)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.activities.BaseReactActivity.onJSBundleReloaded(BaseReactActivity.java:378)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.core.RctManager$CustomDevCommandsHandler.onJSBundleReloaded(RctManager.java:191)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.reactnativenavigation.core.RctManager$CustomDevCommandsHandler.onJSBundleLoadedFromServer(RctManager.java:181)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:660)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-11 01:59:44.994 16169-16169/com.livepay W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by guyca** [comment]
@beast What version of react native do you use?

**Comment by beast** [comment]
React Native 0.27.0

**Comment by guyca** [comment]
Hey @beast `mAttachScheduled` was removed in this commit https://github.com/facebook/react-native/commit/a69b8835373c9b1fcb7d31032d6f384a7b6f0478

If temporarily downgrading to version 0.25 is ok with you, I suggest you do that, until we migrate this project to current versions of RN.
