### ISSUE TITLE
[iOS] ScrollView/FlatList *BUG* after changing route/pushing/showing modal while there is a momentum scroll

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#1446]
### Issue Description

There is a bug when you have a `ScrollView` / `FlatList` (haven't tried with others) on one screen and you switch (/ push / show) to a different screen while `ScrollView` / `FlatList` is scrolling with a momentum, when you return back to the prev. screen (screen with `ScrollView` / `FlatList`) it's children / cells would not respond to touches until: a) you scroll `ScrollView`to the end/top (with a bounce) b) the cell item re-renders (FlatList)

### Steps to Reproduce / Code Snippets / Screenshots

https://github.com/grundmanise/react-native-navigation-scrollview-bug
1. Scroll few items (ScrollView should not bounce, i.e. do not scroll till the end of the list)
2. While there is a momentum scrolling => switch to the 2nd tabbar screen
3. Return to the 1st screen and try to click a `FlatList` cell => cells are not responsive.

---
### Environment
* React Native Navigation version: 1.1.104
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, 10.3,  Debug & Release

**Comment by varungupta85** [comment]
+1 I am able to reproduce this issue in the app. I have seen it a couple of times earlier also but I couldn't put a finger on the steps to reproduce. Thanks @grundmanise for pinpointing the issue. I am not sure if this has always been there or introduced later.

**Comment by varungupta85** [comment]
@DanielZlotin Do you guys also face this bug in the Wix app?

**Comment by guyca** [comment]
@gran33 Think you could look into this during guild day tomorrow? It's reproduces constantly in our app as well.

**Comment by gran33** [comment]
@DanielZlotin yes. I can reproduce it over and over again. 

I try to put some light on this limbo case (yes super important). 
Any extra info will be appreciated.

**Comment by guyca** [comment]
Fixed in v1.1.169

**Comment by blairvanderhoof** [comment]
I think this is still broken for TextView

![image](https://user-images.githubusercontent.com/833890/28904693-9ddab564-77c1-11e7-9940-06f7db03229f.png)


```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTTextView scrollViewDidEndDecelerating:]: unrecognized selector sent to instance 0x7fd51a0641c0'

```

**Comment by blairvanderhoof** [comment]
Here is a suggested patch https://github.com/wix/react-native-navigation/compare/master...blairvanderhoof:patch-1

**Comment by varungupta85** [comment]
I also experienced the crash that @blairvanderhoof reported.
