### ISSUE TITLE
largeTitle attribute with textColor & textFontFamily doesn't work

### ISSUE THREAD

**Issue by anonrig** [wix/react-native-navigation#2394]
### Issue Description

Using largeTitle attribute on topBar with textColor & textFontFamily doesn't work. Removing largeTitle attribute removes the problem.

## Using large titles: 

```javascript
import React, {Component} from 'react';
import Navigation from 'react-native-navigation';

export default class LoginView extends Component {
  static navigationOptions = {
    topBar: {
      title: 'Login',
      hidden: false,
      textFontFamily: 'Avenir Next',
      textColor: 'red',
      largeTitle: true
    }
  }

  render() {
    return ();
  }
}
```

![img_6327](https://user-images.githubusercontent.com/1935246/34321653-a570282a-e825-11e7-952b-84e397ef8236.PNG)

## Without using large titles

```javascript
import React, {Component} from 'react';
import Navigation from 'react-native-navigation';


export default class LoginView extends Component {
  static navigationOptions = {
    topBar: {
      title: 'Login',
      hidden: false,
      textFontFamily: 'Avenir Next',
      textColor: 'red'
    }
  }

  render() {
    return ();
  }
}
```

![img_6326](https://user-images.githubusercontent.com/1935246/34321666-fbde9e9e-e825-11e7-8e05-0c7179a27edf.PNG)

---
### Environment
* React Native Navigation version: react-native-navigation@alpha
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS 
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X

**Comment by pqkluan** [comment]
Your issue is lacking in details, please update the info following the issue described below.

```
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT
```

**Comment by anonrig** [comment]
@pqkluan Updated issue with images and description.

**Comment by anonrig** [comment]
@bogobogo any information about this?

**Comment by bogobogo** [comment]
@anonrig #2411 should fix this. Let me know if you have any problems.

**Comment by frangeris** [comment]
@bogobogo still having this issue, `"react-native-navigation": "^1.1.365",`

```javascript
export default class Recents extends Component {
  static navigatorStyle = {
    largeTitle: true,
    navBarTextColor: 'blue'
  }
```

![image](https://user-images.githubusercontent.com/811381/35773710-7d14c0fa-0938-11e8-85bc-80c16875860a.png)
