### ISSUE TITLE
How to disable sideMenu on current screen?

### ISSUE THREAD

**Issue by DVLNarayana** [wix/react-native-navigation#2621]
### Issue Description
How to disable sideMenu on current window even user swipe right or left on the screen

### Environment
* React Native Navigation version: 2.0.2016 (V2)
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by odesey** [comment]
In your screen constructor add the following:

```javascript
    this.props.navigator.setDrawerEnabled({
      side: "left",
      enabled: false,
      screen: "Drawer"
    });
```

**Comment by pqkluan** [comment]
This feature is in the [document](https://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-)

**Comment by DVLNarayana** [comment]
@pqkluan I am looking for the solution in RNN V2 not in V1

**Comment by maestrolsj** [comment]
I have same issue

**Comment by diegolmello** [comment]
I'm migrating from react-navigation and looking for this feature too.
IMO, it shouldn't be done on setRoot as mentioned/tried above.
It should be on `static get options` or even something like `setDrawerEnabled` from v1.
Thanks :)

**Comment by maestrolsj** [comment]
same issue  it doesn't work on Android

**Comment by yogevbd** [comment]
Should be fixed now. thanks!

**Comment by sapjax** [comment]
@yogevbd 
Do you familiar with Android development?
There are too many bugs on Android,  but the fix progress is slow, I feel desperate.
I hope you can do some work on Android because the iOS version is almost perfect.

**Comment by sJJdGG** [comment]
@yogevbd this issue has only been resolved on ios.
It still does not work on android. i both checked by testing and looking at the source code.
shouldn't this issue be reopend as there is no android implementation and the the issue indicates on both platforms.
I'm saying this because it was part of the project and now it went to the Done category and looks like it has both platforms covered.

**Comment by reganperkins** [comment]
not to be a pain but this is turning into a major issue in our application. Is there a guess on when we might see this added? As a work around I have tried to use the react-native's DrawerLayoutAndroid but react-native-navigations modals seems to mess it up (the ref links seem to return undefined for the drawer after opening a modal)

**Comment by gianlucaparadise** [comment]
Any chance to have this fixed on Android?

**Comment by mayconmesquita** [comment]
You can use this to disable sideMenu:
```javascript
Navigation.mergeOptions(this.props.componentId, {
  sideMenu: {
    left: {
      enabled: false
    }
  }
});
```
And this to enable:
```javascript
Navigation.mergeOptions(this.props.componentId, {
  sideMenu: {
    left: {
      enabled: true
    }
  }
});
```

**Comment by bonnmh** [comment]
static options(passprops) {
    return {
      topBar: {
        visible: false,
        drawBehind: true
      } , 
      sideMenu : {
        right : {
          visible : false , 
          enabled : false
        }
      }
    };
  }
