### ISSUE TITLE
[IOS] Keyboard flickering while pushing screen with autofocus TextInput

### ISSUE THREAD

**Issue by ACOSW** [wix/react-native-navigation#2622]
### Issue Description

Keyboard flicks while pushing screen with autofocus TextInput. Flickering appears only with default ios animation (horizontal-slide), with "fade" animation keyboard appears fine.

### Steps to Reproduce / Code Snippets / Screenshots

Simply push to the navigation stack new screen with autofocus input and you'll see same keyboard flickering as on attached gif image:

<img src="https://user-images.githubusercontent.com/6252660/35678320-e1e6ad44-0763-11e8-834a-73217c8754c5.gif" width="300">

---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, ios 10/11, Debug and Release,

**Comment by pqkluan** [comment]
This problem happens because the second screen is mounted before the push-animation finished. 
All native events (include keyboards) are share between Screens.

This issue could be solved by using fade animation or delay the TextInput from rendering too soon.

**Comment by untoldone** [comment]
@pqkluan is there a way to have a text input autofocused and the keyboard skip animation on a new screen without a fade in or flickering?

For example, many apps have this such as Facebook messenger and others (when you select a chat, input is focused and keyboard is up on new screen before transition.

**Comment by DVSoftware** [comment]
We also have this issue, it's pretty annoying that we have to delay input focusing

**Comment by Jose4gg** [comment]
This needs to be fixed

**Comment by pribeh** [comment]
Same. Adding a timeout seems to be the only fix for now.

**Comment by LRNZ09** [comment]
I'm also having this issue.

**Comment by exentrich** [comment]
No better solution besides timeout? Will be awesome if RNN itself fix this problem, because **everyone** could face this glitch.
Also in modals use of autoFocus makes view empty for duration of appear animation. This adds annoying delays before screen body actually showed.

**Comment by chrise86** [comment]
The way I'm getting around it is to remove the `autoFocus` from the input and instead add a ref:
```
<Input ref={ref => this.input = ref} />
```
then setup an event listener and focus when the screen appears:
```
class MyComponent extends Component {
  componentDidMount() {
    this.navigationEventListener = Navigation.events().bindComponent(this)
  }

  componentWillUnmount() {
    // Not mandatory
    if (this.navigationEventListener) {
      this.navigationEventListener.remove()
    }
  }

  componentDidAppear() {
    if (this.input) this.input.focus()
  }
}
```

**Comment by ATShiTou** [comment]
>   componentDidMount() {
>     this.navigationEventListener = Navigation.events().bindComponent(this)
>   }
> 
>   componentWillUnmount() {
>     // Not mandatory
>     if (this.navigationEventListener) {
>       this.navigationEventListener.remove()
>     }
>   }
> 
>   componentDidAppear() {
>     if (this.input) this.input.focus()
>   }

It's not working for me.

**Comment by cuongtranduc** [comment]
I still get this issue, does anyone have a solution? I dont want to set a timeout

**Comment by chrise86** [comment]
@ATShiTou how are you creating your ref?

**Comment by ATShiTou** [comment]
I had resolved my problem. Mine is `showOverlay` problem, not `push`. Thank you anyway.

**Comment by pribeh** [comment]
@chrise86 's solution is the best for now but this is still happening for us.

**Comment by BDomantas** [comment]
Why is this closed?  It's still an issue in 3.2.0

**Comment by leonid-shevtsov** [comment]
I have slightly different behavior in my app: when I push a screen with an autofocused input, the screen animates without the keyboard, then jumps back 1/4 of the screen, but now with the keyboard visible, and completes the push animation again. So it kind of jerks back and forth.

**Comment by exentrich** [comment]
Try to set `animations: {push:{waitForRender: true}}` in `static options=...` for screen where you have autofocus input

**Comment by soroush-b** [comment]
I fixed that by 
``` 
  componentDidMount() {
    this.navigationEventListener = Navigation.events().bindComponent(this);
  }

  componentWillUnmount() {
    // Not mandatory
    if (this.navigationEventListener) {
      this.navigationEventListener.remove();
    }
  }

  componentDidAppear() {
    this.input.focus();
  }
```

**Comment by chrise86** [comment]
@soroush-b that’s the solution I posted above. For those saying it’s still an issue, I’m not sure there is anything that can be done to “fix it” other than solutions like this. As @pqkluan said early on, it’s due to the component mounting before the native animation is complete.

**Comment by JohnSmith0602** [comment]
> Try to set `animations: {push:{waitForRender: true}}` in `static options=...` for screen where you have autofocus input

Your solution works in RNN v2.27.9, thanks!

**Comment by L-Yeiser** [comment]
waitForRender removed the animation entirely. As in with that configuration `autofocus` just stopped working.

**Comment by pontusab** [comment]
Still an issue in the latest versions.

**Comment by nenjamin2405** [comment]
I'm still having problem with this. how can I resolve it :(

**Comment by nenjamin2405** [comment]
The current approach that I use:

If your app is using a custom InputField:

```
import {useNavigationComponentDidAppear} from 'react-native-navigation-hooks';

const CustomInputField = ({shouldAutoFocus}) => {
       const inputRef = useRef(null);

       useNavigationComponentDidAppear(() => {
          if (shouldAutoFocus) {
             inputRef.current && inputRef.current.focus();
          }
       });

       return (
        <TextInput
          ref={inputRef}
          {...restProps}
        />
       )
      
}
```

And wherever you use CustomInputField: `<CustomInputField shouldAutoFocus />`

**Comment by Peeeep** [comment]
Old thread, I’m aware, but I thought leaving this here might help people who use functional components:

```
import {useNavigationComponentDidAppear} from 'react-native-navigation-hooks';

…

/**
 * Focus input once screen has appeared for the first time
 */
const inputRef = useRef(null);
const shouldAutoFocus = useRef(true);
useNavigationComponentDidAppear(() => {
  if (shouldAutoFocus.current) {
    inputRef.current?.focus();
    shouldAutoFocus.current = false;
  }
}, componentId);

…

<TextInput
  ref={inputRef}
  …
/>
```

**Comment by minhphung210** [comment]
`
    componentDidMount() {
            InteractionManager.runAfterInteractions(() => {
                 inputRef.current?.focus();
            });
    }
`
work for me

**Comment by ghostgarrix** [comment]
Still an issue with latest versions if we want to avoid using a timeout
