### ISSUE TITLE
Disable default blank view when push to another screen

### ISSUE THREAD

**Issue by hamidhadi** [wix/react-native-navigation#2786]
When I push from view to another, a blank view is appearing and after a short delay, my RN view render.
How can I disable this view and show my RN view immediately after pushing from a screen?
I used `v1.1.5` and `v2.0.0-experimental.178` of RNN before, but I didn't have this problem and all of my views were appeared immediately after navigating between screens.

**Comment by guyca** [comment]
Hey @hamidhadi 
This was a design shortcomings in v1 on iOS and was addressed in v2. At this point, we're trying to focus on v2 so this issue won't be addressed.
If it's any consolation, We're on schedule to release v2 to beta by late march/early april.

**Comment by MichaelAmoabengVaulitions** [comment]
@guyca I still see the same thing happening in v2. Is there a solution for this?

**Comment by ithustle** [comment]
Same here
