### ISSUE TITLE
[v2] SideMenu is overflowing Safe Area

### ISSUE THREAD

**Issue by diegolmello** [wix/react-native-navigation#3418]
### Issue Description

Hey, guys.
First of all: you are doing a great work here.
We all appreciate your effort.

I'm developing a Sidemenu and it's Safe Area doesn't seem to work properly.
I tried a lot of margin and RN's SafeAreaView without any luck :(
It start on the top (behind the DeviceStatusBar) and if I swipe a little bit it shows the View correctly.

### Steps to Reproduce / Code Snippets / Screenshots
![jun-22-2018 01-10-08](https://user-images.githubusercontent.com/804994/41757606-7f85e95c-75b9-11e8-80f9-543eb191de49.gif)

If you need a sample I can write one, but I think the gif does the job, right?

Thanks for your help.

---
### Environment
* React Native Navigation version: 2.0.2362
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator iPhone X 11.4 on debug

**Comment by yogevbd** [comment]
Fixed. thanks!

**Comment by diegolmello** [comment]
@yogevbd Just confirming that it's working. Thank you! :)

**Comment by diegolmello** [comment]
@yogevbd Can you fix it on v1 too?

I started migrating from react-navigation to react-native-navigation v2, but it's very unstable on Android unfortunately.
So I switch to v1. Still have some issues, but it's more stable.

**Comment by nbolender** [comment]
Seeing this again in 2.7.1

**Comment by avario** [comment]
I'm also seeing this in 2.8.0 with a tab bar in the center view.

**Comment by MomenYasser** [comment]
Guys i'm still facing it in 3.2.0 ! :D

**Comment by kabus202** [comment]
still existing on 4.0.3 @diegolmello did you find a solution?

**Comment by doneitas** [comment]
Hey guys, I am still facing it on 6.4.0 after setting sidemenu width
