### ISSUE TITLE
[V2] Pass props in top bar custom title component is not working on android 

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#3498]
### Issue Description

Using custom component in the top bar title is working on android and iOS but passing props is only working on iOS, on android it's giving that the passed prop is undefined

### Code Snippets / Screenshots

```js
this.props.navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {
          component: {
            name: "components.CityTopBarTitle",
            id: "components.CityTopBarTitle",
            alignment: "center",
            passProps: {
              city: this.props.selectedCity.name,
              onPress: () => this._presentCityModal()
            }
          }
        }
      }
    })
```

<img width="216" alt="screen shot 2018-07-04 at 8 13 38 pm" src="https://user-images.githubusercontent.com/9201625/42289176-c1a76d1c-7fc6-11e8-8b7e-04addb9fb4c5.png">

---
### Environment
* React Native Navigation version: 2.0.2385
* React Native version:  0.54.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by KJ-Chiu** [comment]
Does anyone have the solution? I got the same problem.

**Comment by Milesc22** [comment]
I noticed this a few days ago as well.

**Comment by stonecold123** [comment]
Yes, same issue with `2.0.2418`

**Comment by jarrx** [comment]
A restart of the app on devices solved it for me. Seems like you have to restart the app on device every time you change the passProps object.

**Comment by hisothreed** [comment]
@yogevbd please i need a solution, going production i can't let that happen 😭

**Comment by brandons** [comment]
Anyone find a solution to this yet?

**Comment by stonecold123** [comment]
The error still occurs in `2.0.2463`

**Comment by hisothreed** [comment]
that should be solved just an hour ago, see the last commit on v2 branch, please let me know if it's working just to close the issue

**Comment by zabojad** [comment]
To me it is still not working: https://github.com/wix/react-native-navigation/issues/4924

**Comment by gustavogialim** [comment]
Same problem, I've heard of a commit that fixes the issue, but it's with you on a Pull Request that is locked.

**Commit:**
https://github.com/wix/react-native-navigation/pull/3897/commits/c7cb591c3fad3bbdfc91085691cb89012ec03923

**Environment:**
"react-native-navigation": "^ 3.6.0"

Any news?

**Comment by Rybachello** [comment]
Is this fixed?

**Comment by guyca** [comment]
Yes.
