### ISSUE TITLE
[v2] android build failure with react-native 0.56.0

### ISSUE THREAD

**Issue by ujwal-setlur** [wix/react-native-navigation#3505]
### Issue Description

android build fails with:
```
> Task :react-native-navigation:compileReactNative55DebugJavaWithJavac FAILED
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java:16: error: JsDevReloadHandler is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class JsDevReloadHandler implements DevBundleDownloadListener {
       ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java:38: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java:7: error: ReloadHandler is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class ReloadHandler implements JsDevReloadHandler.ReloadListener, DevBundleDownloadListener {
       ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java:26: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java:7: error: DevBundleDownloadListenerAdapter is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class DevBundleDownloadListenerAdapter implements DevBundleDownloadListener {
       ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:33: error: method onSuccess in interface DevBundleDownloadListener cannot be applied to given types;
                bundleListener.onSuccess();
                              ^
  required: NativeDeltaClient
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
```

---
### Environment
* React Native Navigation version: 2.0.2397
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by jp928** [comment]
+1

**Comment by ujwal-setlur** [comment]
iOS build is fine.

**Comment by ujwal-setlur** [comment]
@emiyake, I tried your patch, and the compilation goes through, but I am getting an error on android when the app loads. On iOS, it is just fine. I am not sure whether this is related to this issue

<img width="279" alt="screen shot 2018-07-06 at 1 41 19 pm" src="https://user-images.githubusercontent.com/5835869/42399354-54b00c0c-8122-11e8-9ea3-d0d8068fb5b0.png">

**Comment by emiyake** [comment]
As a workaround try to downgrade to `react-native-navigation@2.0.2395`

**Comment by ujwal-setlur** [comment]
Will try that later tonight. Did something go into 2.0.2397 that works cause this?

**Comment by emiyake** [comment]
Yes, this is the issue: 
https://github.com/wix/react-native-navigation/commit/50fd77ec82a0d287799f15193d81fb9544f0bb96#diff-9fa2730ac48819277a0f96ccb7b11a9e

**Comment by ujwal-setlur** [comment]
@emiyake, I tried rnn-2.0.2395, and I could build it with rn-0.56.0 fine without having to apply your pull-request, but I still get the same react error on app load as seen in the screenshot above. I was not getting this with rn-0.55.4. This is happening only on android, and not iOS.

**Comment by ujwal-setlur** [comment]
OK, I think this is something specific to my environment. I stripped it down to a very basic app, and it loads ok.

**Comment by ujwal-setlur** [comment]
It turns out there was a polyfill I was using on android that was causing this:

```js
import "core-js/es6/symbol";
```

**Comment by ujwal-setlur** [comment]
Yep, that's resolved with your change. The other problem I described was due to my use of a polyfill. 

https://github.com/facebook/react-native/issues/18542

**Comment by stokesbga** [comment]
Im seeing this on 2.0.2404

**Comment by alexxsanchezm** [comment]
To deal with this issue, I did:
```
// path: node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java
/* modify onSuccess() with onSuccess(@Nullable NativeDeltaClient nativeDeltaClient)
@Override
    public void onSuccess(@Nullable NativeDeltaClient nativeDeltaClient) {
        UiUtils.runOnMainThread(reloadListener::onReload);
    }
```
```
//path: node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/DevBundleDownloadListenerAdapter.java
/* change onSuccess() with onSuccess(@Nullable NativeDeltaClient nativeDeltaClient) */
@Override
    public void onSuccess(@Nullable NativeDeltaClient nativeDeltaClient) {
    }
```
```
//path: node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java
/* Here just passed down the nativeDeltaClient instance */
@Override
public void onSuccess(NativeDeltaClient nativeDeltaClient) {
    if (bundleListener != null) {
        bundleListener.onSuccess(nativeDeltaClient);
    }
}
```
```
//path: node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/ReloadHandler.java
/* add nativeDeltaClient to onSuccess() */
@Override
public void onSuccess(@Nullable NativeDeltaClient nativeDeltaClient) {
    onReloadListener.run();
}
```
That solved the issue, off course I'm just guessing... but worked for me. But it seemed like the interfaces signatura have changed but not its implementations, looks like a bad merge.

**Comment by stokesbga** [comment]
I made the same changes in my own fork of 2.0.2404 and its all good. yeah must be bad merge ^

**Comment by ujwal-setlur** [comment]
I don't believe @emiyake's PR has been merged.

**Comment by dorthwein** [comment]
Just to clarify - is there a pending fix for this??

**Comment by ujwal-setlur** [comment]
I hope so, because otherwise, rnn can't build with rn-0.56.0. I am currently using @emiyake's patch with patch-package

**Comment by haswalt** [comment]
Looks like the patch was merged and a version with the change is on NPM however I still get the error.

**Comment by ujwal-setlur** [comment]
I will check in just a bit, but make sure you actually got the latest version. That has tripped me up sometimes, particularly if you have yarn.lock or package-lock.json lying around

**Comment by ujwal-setlur** [comment]
This is now resolved in 2.0.2418, but please note comment above. Documentation needs to be updated

**Comment by haswalt** [comment]
@ujwal-setlur I still can't get this to build. Tried a fresh project, followed setup instructions with change above for reactNative56 and i get the same error messages.

It happens during this task: ```Task :react-native-navigation:compileReactNative51ReleaseJavaWithJavac FAILED```. It looks like both ```Task :react-native-navigation:compileReactNative56ReleaseJavaWithJavac``` runs correctly first.

**app/build.gradle**
```
compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.kitchensink"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative56"
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**build.gradle**
```
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 25
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

**Comment by haswalt** [comment]
note this is the issue reported here: https://github.com/wix/react-native-navigation/issues/3388#issuecomment-402637025

**Comment by haswalt** [comment]
If I delete the productFlavours that i'm not using from the lib I have no issues building, unfortunately I don't know enough about android and gradle to work out why al productFlavors are being built

**Comment by ujwal-setlur** [comment]
@haswalt, are you doing a debug build or release build? Let me try on a fresh protect as well

**Comment by haswalt** [comment]
Release build. For those hitting this issue i'm using patch-package and this patch:

```
--- a/node_modules/react-native-navigation/lib/android/app/build.gradle
+++ b/node_modules/react-native-navigation/lib/android/app/build.gradle
@@ -48,12 +48,6 @@ android {
     }
     flavorDimensions "RNN.reactNativeVersion"
     productFlavors {
-        reactNative51 {
-            dimension "RNN.reactNativeVersion"
-        }
-        reactNative55 {
-            dimension "RNN.reactNativeVersion"
-        }
         reactNative56 {
             dimension "RNN.reactNativeVersion"
         }
```

**Comment by haswalt** [comment]
same with debug build

**Comment by sytolk** [comment]
@haswalt this is different issue. Try this fix: https://github.com/wix/react-native-navigation/issues/3388#issuecomment-399071604

**Comment by billel-boudchicha** [comment]
@sytolk hey just update to 2.0.2435
still the issue

**Comment by herarya** [comment]
solved 👍 
 `  "react-native": "0.56.0",`
` "react-native-navigation": "^2.0.2427",`

**Comment by ujwal-setlur** [comment]
I will close this as this seems to be working. Works for me at least...

**Comment by abury** [comment]
I'm still getting this issue. I'm running RNN `2.0.2427` with RN `0.56.0` and debug build works fine, however a release build fails with the above issues.

**Comment by abury** [comment]
we were using `app:assembleDebug` but weren't passing the `app` prefix for the release build. We've added this and the build issues seem to have been resolved 👍

**Comment by ionush** [comment]
I'm also still getting this issue. Running RN 0.56 with RNN 2.0.2577. Also tried latest version 2.0.2582. All the above solutions don't work. Any suggestions?

**Comment by phantom1299** [comment]
For me, debug was working but release was failing with above issue. The solution was to [add filter](https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=_82-ignore-other-rnn-flavors) for reactNative57 too because the error message was containing stuff with 

> generateReactNative57ReleaseRFile
