### ISSUE TITLE
[V2] [iOS] Sidemenu layout inside bottomTabs layout weird behaviour

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#3697]
### Issue Description

Sidemenu layout inside bottomTabs layout bugs out on iOS. The icon disappears and a black bar appears under as if it is miscalculating the bottomTabs height. Works perfectly on Android.
I also noticed that merging options for the sidemenu layout on iOS fails. So trying to open/close the sidemenu with a button using the sidemenu's components ID fails. 

### Steps to Reproduce / Code Snippets / Screenshots

Notice how the icon dissapears and there is a black bar?

Layout looks like:
```js
    root: {
      bottomTabs: {
        children: [
          { // Tab 1 - Homescreen
            stack: {
              children: [
                {
                  component: {
                    name: 'baseNet.HomeTab',
                  },
                },
              ],
              options: {
                bottomTab: {
                  text: 'Home',
                  icon: loadedIconSource['fa-home'],
                },
              },
            },
          },
          { // Tab 2 - Email <---- THIS ONE GIVES PROBLEMS
            sideMenu: {
              id: 'baseNet.EmailSideMenu',
              left: {
                component: {
                  name: 'baseNet.EmailSideMenu',
                },
              },
              center: {
                stack: {
                  children: [
                    {
                      component: {
                        name: 'baseNet.EmailTab',
                      },
                    },
                  ],
                },
              },
              options: {
                bottomTab: {
                  text: 'Email',
                  icon: loadedIconSource['fa-envelope-o'],
                },
              },
            },
          },
          { // Tab 3 - Calendar
            stack: {
              children: [
                {
                  component: {
                    name: 'baseNet.AgendaTab',
                  },
                },
              ],
              options: {
                bottomTab: {
                  text: 'Agenda',
                  icon: loadedIconSource['fa-calendar'],
                },
              },
            },
          },
          { // Tab 4 - Hours
            stack: {
              children: [
                {
                  component: {
                    name: 'baseNet.HourTab',
                  },
                },
              ],
              options: {
                bottomTab: {
                  text: 'Hours',
                  icon: loadedIconSource['fa-clock-o'],
                },
              },
            },
          },
          { // Tab 5 - More
            stack: {
              children: [
                {
                  component: {
                    name: 'baseNet.MoreTab',
                  },
                },
              ],
              options: {
                bottomTab: {
                  text: 'More',
                  icon: loadedIconSource['fa-bars'],
                },
              },
            },
          },
        ],
      },
    },
```
DRAWER CLOSED:
![simulator screen shot - iphone 8 - 2018-08-06 at 13 57 59](https://user-images.githubusercontent.com/4223434/43715447-d23e60f8-9980-11e8-9225-d6c85254f023.png)

DRAWER OPENED:
![simulator screen shot - iphone 8 - 2018-08-06 at 14 00 03](https://user-images.githubusercontent.com/4223434/43715539-112a3256-9981-11e8-90d2-2d9cacc7b176.png)

---
### Environment
* React Native Navigation version: 2.0.2456
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info:
iOS 11.4.1
Simulator + Device
Debug

**Comment by ItsNoHax** [comment]
Latest RNN: 2.-0.2486: Just crashes now

![simulator screen shot - iphone 8 - 2018-08-23 at 15 08 15](https://user-images.githubusercontent.com/4223434/44527171-601cf700-a6e6-11e8-91b9-482326655518.png)

**Comment by ItsNoHax** [comment]
@guyca Have you had time to look at this?

**Comment by yogevbd** [comment]
Fixed in #3962

**Comment by ItsNoHax** [comment]
@yogevbd This is still not fixed unfortunately. Build number: 2564 produces the following:
The black bars are now gone but the icons are still dissapearing and merge options no longer work. (you can only drag the sidemenu open)
![image from ios 1](https://user-images.githubusercontent.com/4223434/46085919-6c91e500-c1a7-11e8-82b6-2ddc7dbec536.jpg)

**Comment by ItsNoHax** [comment]
Some sort of invisible bottomtab measurement is going on, atleast it seems the same size as the bottomtab:
![peek 2018-10-02 16-52](https://user-images.githubusercontent.com/4223434/46356807-c856e500-c663-11e8-9e98-77a611d138e8.gif)

**Comment by yogevbd** [comment]
Fixed here: b840dd4, v2.0.2571.
Can you please check that this fix does work for you and approve? thanks!

**Comment by ItsNoHax** [comment]
@yogevbd Last 2 releases has broken this again. It seems the bottomTabs that have a sideMenu layout inside them act weird when they are selected.

**Comment by yogevbd** [comment]
Can you give more details? how does your layout looks like?

**Comment by ItsNoHax** [comment]
I have 5 bottomTabs and 2 of them (Email + Agenda have a sidemenu layout inside them.

When a bottomTab is selected that doesn't have a sidemenu layout.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 28](https://user-images.githubusercontent.com/4223434/47283879-63006f00-d5e5-11e8-8d8d-b658aed6ff72.png)

When a bottomTab is selected that does have a sidemenu layout.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 36](https://user-images.githubusercontent.com/4223434/47283922-93480d80-d5e5-11e8-8967-7fca0a0ee0fb.png)

**Comment by ItsNoHax** [comment]
I have 5 bottomTabs and 2 of them (Email + Agenda have a sidemenu layout inside them.

When a bottomTab is selected that doesn't have a sidemenu layout.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 28](https://user-images.githubusercontent.com/4223434/47283879-63006f00-d5e5-11e8-8d8d-b658aed6ff72.png)

When a bottomTab is selected that does have a sidemenu layout.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 36](https://user-images.githubusercontent.com/4223434/47283922-93480d80-d5e5-11e8-8967-7fca0a0ee0fb.png)

**Comment by ItsNoHax** [comment]
So I have a sidemenu layout inside 2 of my bottomTabs.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 28](https://user-images.githubusercontent.com/4223434/47284002-ddc98a00-d5e5-11e8-9bac-0949d8f40c3b.png)

But when a tab is selected that has a sidemenu layout the whole bottomBar goes like grey?

![simulator screen shot - iphone x - 2018-10-22 at 10 27 36](https://user-images.githubusercontent.com/4223434/47284006-e5892e80-d5e5-11e8-9ba7-7d9cfc5cd0ad.png)

**Comment by ItsNoHax** [comment]
So I have a sidemenu layout inside 2 of my bottomTabs.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 28](https://user-images.githubusercontent.com/4223434/47284002-ddc98a00-d5e5-11e8-9bac-0949d8f40c3b.png)

But when a tab is selected that has a sidemenu layout the whole bottomBar goes like grey?

![simulator screen shot - iphone x - 2018-10-22 at 10 27 36](https://user-images.githubusercontent.com/4223434/47284006-e5892e80-d5e5-11e8-9ba7-7d9cfc5cd0ad.png)

**Comment by ItsNoHax** [comment]
So I have bottomTabs but 2 of the tabs have a sidemenu layout inside them. This allows me to have custom drawers for 2 of the tabs. (I previously sent in a PR that added this layout to the playground app under complex layouts)

This was recently working fine untill now, it seems when I click on a tab that has a sidemenu layout, the whole bottomTab goes grey.

![simulator screen shot - iphone x - 2018-10-22 at 10 27 36](https://user-images.githubusercontent.com/4223434/47284102-53355a80-d5e6-11e8-8545-5e523d85937e.png)

**Comment by yogevbd** [comment]
It's because `bottomTabs.drawBehind` is false. changing it to `bottomTabs.drawBehind: true` will fix this

**Comment by ItsNoHax** [comment]
@yogevbd I can confirm this fixes the error but I don't see how it makes sense. I don't want to drawBehind my bottom tabs because then the last item on my list (screenshot above) is not visible.

**Comment by yogevbd** [comment]
The real problem is that `bottomTabs.translucent` was true by default. we changed it to be false. 
That's why the bottomTabs is half transparent and you can see the view behind it, something you want to avoid when setting `bottomTabs.drawBehind: false`
