### ISSUE TITLE
[Android] Can not retrieve the URL using Linking.getInitialURL() when new incoming intent data received.

### ISSUE THREAD

**Issue by karkb** [wix/react-native-navigation#384]
### Issue Description

Hi, 

First, Thanks for such a great work & effort on this project.
I am trying to link to specific screens in my project by using custom external URL.
### Steps to Reproduce / Code Snippets / Screenshots

What I did so far:
- Add intent filters to respond to action requests from other applications.

``` xml
<intent-filter android:label="filter_react_native">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="deeplink" android:host="home" />
</intent-filter>
```
- By using Linking in react native API, i am trying to access any incoming intents.

``` js
componentDidMount() {
  const url = Linking.getInitialURL().then(url => {
    if (url) {
      console.warn(url);
    }
  });
}
```
- The result & issue:
  This will open my app but the issue is that i can not use getInitialURL for receiving the new intent data in order to navigate to the screen needed.
- When the app is closed and navigate to it from external link.
  <img width="1296" alt="screen shot 2016-10-18 at 4 14 40 pm" src="https://cloud.githubusercontent.com/assets/20394467/19469500/2b1b346e-954e-11e6-8068-e4177310af94.png">
- When the app is open in background.
  <img width="1346" alt="screen shot 2016-10-18 at 4 28 24 pm" src="https://cloud.githubusercontent.com/assets/20394467/19469959/2f7c1850-9550-11e6-987f-1017a360ae00.png">
### Environment
- React Native Navigation version: 2.0
- React Native version: 0.33
- Platform: Android
- Device info: Device Mi 5/ Marshmallow 6.0

**Comment by guyca** [comment]
Where did you declare the intent filter? Can you please paste the entire declaration of the activity associated with this intent filter?

**Comment by beast** [comment]
Hi, @guyca. @karkb is our intern who is working on the Android part of our app. He is currently travelling so I will follow up on the issue. You are correct that the intent filter is declared in android manifest under mainactivity. I looked at the Android Navigation Source Code I do see what you are talking about. Could we do something like the following?

```java
      <activity
        android:name="com.reactnativenavigation.controllers.NavigationActivity" />
```

**Comment by guyca** [comment]
Hey @beast 
It won't work since NavigationActivity relies on SplashActivity to start react. If you define the intent filter there you'll see a white screen when the app starts (or a crash :)).
At any case, I just pushed .134. Can you update and see how it works for you?

Just a few things to note:
* Make sure you **don't** have `android:launchMode="singleTask"` defined in your MainActivity
* You'll need to rely on `AppState` as well in order get the deepLink when the app is opened after it's already created (app was running in background). Something like this:
  ```js
constructor(props) {
    super(props);
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
    this.state = {
      currentAppState: AppState.currentState
    };
    this._handleAppStateChange = this._handleAppStateChange.bind(this);
  }

  componentDidMount() {
    console.log('FirstTabScreen', 'componentDidMount');
    AppState.addEventListener('change', this._handleAppStateChange);
    this._checkDeepLink();
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange);
  }

  _handleAppStateChange(currentAppState) {
    this.setState({currentAppState});
    if (Platform.OS === 'android') {
      this._checkDeepLink();
    }
  }

  _checkDeepLink() {
    Linking.getInitialURL().then(url => {
      if (url) {
        console.warn(url);
      }
    });
  }
  ```
* This will change once when we finally add screen lifecycle methods. You won't check deep link in `componentDidMount` and with `AppState`, instead we'll be able to stick all that logic in `onDisplayed` or something like that.

**Comment by beast** [comment]
@guyca Wow, I can't thank you enough for the detailed reply. I'll definitely have a try and revert back to you. I still have some backend testing to write at the moment. I will let you know soonest if this works. I am going to try both Android App Links and iOS Universal Link and let you know how it works with the package. Thanks again for the great package.

**Comment by guyca** [comment]
Closing this. Let me know if it doesn't work

**Comment by maxs15** [comment]
Hey @guyca.
I'm having the same issue (but I'm using [react-native-branch-deep-linking](https://github.com/BranchMetrics/react-native-branch-deep-linking) instead of AppState).
Could you let me know where I should put the intent filter if it isn't in the MainActivity ?

Thanks

**Comment by guyca** [comment]
@maxs15 I assume you're referring to `Branch.getAutoInstance(this);`. You can put all your `onCreate` login in `onActivityCreated` callback as shown [here](https://github.com/wix/react-native-navigation/wiki/Android#activity-lifecycle-and-onactivityresult)

**Comment by maxs15** [comment]
I was referring to the intent-filter in the AndroidManifest.xml
```xml
  <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:launchMode="singleTop"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">

        <intent-filter>
            <data android:scheme="craver" android:host="open" />
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
        </intent-filter>
```
Is it correct to declare it in the MainActivity ?

I'm having issues to make the plugin work with Branch.
I'm calling ``Branch.getAutoInstance(this);`` in the MainApplication onCreate since the method needs the Application context not the activity context.

```java
@Override
  public void onCreate() {
    super.onCreate();

    setActivityCallbacks(new ActivityCallbacks() {
      @Override
      public void onActivityStarted(Activity activity) {
        RNBranchModule.initSession(activity.getIntent().getData(), activity);
      }
    });
    // Init Branch
    Branch.getAutoInstance(this);
  }
```

The plugin README tells me I should override the onNewIntent method as well, but I didn't find how I could do that, looks like I cannot override it in the ActivityCallbacks ?
```java
@Override
public void onNewIntent(Intent intent) {
   this.setIntent(intent);
}
```

I would appreciate your help so much, I don't know if it could be an issue related to the plugin or something I did wrong, desperate to find a solution 😅  

Thanks

**Comment by guyca** [comment]
25da56e3f10f5bd370d671856593d235bdaf721b exposes onNewIntent in ActivityCallbacks. Defining your intent filters in MainActivity should work since it extends SplashActivity which passes the data from the original intent to NavigationActivity.

V2 will have a single activity, this whole process will be much simpler.

**Comment by maxs15** [comment]
Awesome ! Thanks @guyca, will try this out

**Comment by guyca** [comment]
Hey @maxs15 
02a432dba4c8e83736c54cdf1a48c10bc9291cf4 and 7367a8dba1bdcd0346d430633fcd0936f98e149d should call onNewIntent of react instance manager for you, as a result your `Linking.addEventListener(...)` listener should receive an event.

**Comment by maxs15** [comment]
You made my day @guyca !
Thanks you so much, the branch linking is working perfectly now 👍 
However the onNewIntent event isn't called in the ActivityCallbacks on my side..
Guess you're already calling activity.setIntent on your side ? This would make the use of onNewIntent unnecessary for the linking to work.

**Comment by guyca** [comment]
I'm really glad to hear 😄 
I thought about calling `activity.setIntent(activity.getIntent())` but it felt a bit too intrusive. For now, we're only calling `onNewIntent` of the react instance manager which should be enough for RN's Linking module.

**Comment by maxs15** [comment]
Ok, but do you call onNewIntent of the ActivityCallbacks ?
I Tried on my device, I added a log in onNewIntent and it's never called on my side

**Comment by guyca** [comment]
onNewIntent won't be called. I [call onNewIntent of the react instance manager](https://github.com/wix/react-native-navigation/blob/7367a8dba1bdcd0346d430633fcd0936f98e149d/android/app/src/main/java/com/reactnativenavigation/controllers/IntentDataHandler.java#L45).

We can change it so onNewIntent will be called and you'll be able to respond to onNewIntent in native. Is this something you need?

**Comment by maxs15** [comment]
Oh okay I see, just wanted to be sure everything works properly 😄 
I don't need it, thanks for the help @guyca !

**Comment by Elf2707** [comment]
Had the same issue with experimental.183, but when I install experimental.223 it's gone. As I understand getInitialURL won't work in android will always return null. Linking will work through addListener to 'url' event. App will fire this event in NavigationActivity onResume->IntentDataHandler.onPostResume with this fakeOnNewIntentForLinkingModule method, am I right? I just want to understand how things work) Thanks.

**Comment by guyca** [comment]
yes.

**Comment by Elf2707** [comment]
Ok. got it. Thanks again and best regards)

**Comment by enahum** [comment]
can anyone provide an example of how to do this?

Whenever I change this
```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:windowSoftInputMode="adjustResize"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      >
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
      </activity>
```

to this

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:windowSoftInputMode="adjustResize"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      >
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="mattermost" android:host="open" />
          </intent-filter>
      </activity>
```

the app just crashes on load, any pointers?

**Comment by renrizzolo** [comment]
@enahum you keep the main intent filter and add a new one for the scheme.
```
<activity 
 ... 
>
 <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
 </intent-filter>
 <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="mattermost" android:host="open" />
 </intent-filter>
</activity>
```

**Comment by perrosnk** [comment]
@maxs15 Is it possible to share the whole `onCreate` method? I haven't understood how I am supposed to set it up with branch.
Currently my `onCreate` method looks like this:

```java
  @Override
  public void onCreate() {
    super.onCreate();
    setActivityCallbacks(new ActivityCallbacks() {
      @Override
      public void onActivityResult(int requestCode, int resultCode, Intent data) {
          mCallbackManager.onActivityResult(requestCode, resultCode, data);
      }
    });

    FacebookSdk.sdkInitialize(getApplicationContext());
    AppEventsLogger.activateApp(this);
    SoLoader.init(this, /* native exopackage */ false);
    // Branch.getAutoInstance(this);
  }

```

**Comment by reyalpsirc** [comment]
In order to resume the App instead of restarting it, the only way I could have it working was using `Linking.addEventListener('url', this.handleOpenURL)` and setting the code on [this stackoverflow question](https://stackoverflow.com/questions/11721619/resume-the-top-activity-instead-of-starting-the-launcher-activity/21022876#answer-38878907) (even with `launchMode="singleTop"` seems to solve the issue for me) on the MainActivity.

**Comment by bdavid68** [comment]
@maxs15 @guyca `react-native-branch` is working only when app was already in background.
It doesn't work when app was completely closed and re-opened by deep linking.
Could you please help me?
Thanks in advance!

**Comment by oferRounds** [comment]
@bbdroid same here, did you find any solution to this?
