### ISSUE TITLE
[V2] Overlay destruct on setRoot invoke

### ISSUE THREAD

**Issue by hadimostafapour** [wix/react-native-navigation#3860]
### Issue Description

I'm using `showOverlay` to show an overlay, when I try to change stack with setRoot, overlay will be destructed.

### Steps to Reproduce / Code Snippets / Screenshots

1. Set root using Navigation.setRoot(...)
2. Show overlay using Navigation.showOverlay(...)
3. Reset root stack using Navigation.setRoot(...)

---
### Environment
* React Native Navigation version: 2.0.2500
* React Native version: 0,56
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by guyca** [comment]
resolved 2.0.2570

**Comment by mauriciogtaborda** [comment]
This keeps happening to me.

**Comment by bumpingChris** [comment]
I'm still seeing this same issue in version 7.29.0
1. setRoot....
2. showOverlay...
3. setRoot... 

The second setRoot would dismiss the overlay.
