### ISSUE TITLE
await Navigation.showModal doesn't return the componentId

### ISSUE THREAD

**Issue by gran33** [wix/react-native-navigation#3925]
### Issue Description
`await Navigation.showModal` isn't return the `componentId`.

```js
const compId = 
await Navigation.showModal({
    stack: {
      children: [{
        component: {
          id: 'my.screen.id,
          name: 'my.screen.name
          passProps: {...}
        }
      }]
    }
  });
```
`compId` is `undefined
### Steps to Reproduce / Code Snippets / Screenshots
```
await showModal('123', ...);
await dismissModal('123');
showModal('123', ...); // Crash---
```

### Environment
* React Native Navigation version: 2.0.2524
* React Native version:  0.51
* Platform(s) (iOS, Android, or both?):iOS only
* Device info (Simulator/Device? OS version? Debug/Release?): device + simulator, debug + release, all OS versions

**Comment by guyca** [comment]
@gran33 
Can you assign the stack a predefined id?

```js
Navigation.showModal({
    stack: {
      id: 'MyStack'
      children: [{
        component: {
          id: 'my.screen.id,
          name: 'my.screen.name
          passProps: {...}
        }
      }]
    }
  });
```

Then you could dismiss the modal using `Navigation.dismissModal('MyStack');`
Will this be suitable for now?

**Comment by gran33** [comment]
If I do so, that says that the `componentId` already exists.

**Comment by guyca** [comment]
resolved

**Comment by drewmca02** [comment]
I'm still seeing this problem. Don't see how it's resolved b/c there's no code associated with the issue.

**Comment by SudoPlz** [comment]
Still seeing this in `"react-native-navigation": "^2.16.0"`

Any clue as to why that was closed, the error originates here:
https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNModalManager.m#L39

and that's not resolved yet.

**Comment by guyca** [comment]
Fixed in 2.18.0
