### ISSUE TITLE
[V2] setStackRoot causes topBar to overlap over the screen

### ISSUE THREAD

**Issue by 3210jr** [wix/react-native-navigation#4021]
### Issue Description

![whatsapp image 2018-09-24 at 10 27 36](https://user-images.githubusercontent.com/11012023/45940969-bc747e80-bfe4-11e8-9db1-decb7c6576d7.jpeg)

After calling setStackRoot(compId), the next view's topBar overlays the content of the view.

### Steps to Reproduce / Code Snippets / Screenshots

Code:
```
Navigation.setStackRoot(this.props.componentId, {
    component: {
        name: "nomads.nomads.Dashboard",
        passProps: {
            text: "Root screen"
        },
        options: {
            topBar: {
                visible: true,
                buttonColor: "white",
                title: {
                    text: "Nomads",
                    color: "white",
                    fontSize: 24,
                    fontFamily: "JosefinSans-Regular"
                },
                background: {
                    color: primary
                },
                drawBehind: false
            },
            animations: {
                push: {
                    // also tried setStackRoot
                    enable: false
                }
            }
        }
    }
});
```

Thanks!

---
### Environment
* React Native Navigation version: 2.0.2556
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): On Device - Debug version

**Comment by guyca** [comment]
Hey @3210jr, thanks for reporting. Resolved in 2.0.2560

**Comment by 3210jr** [comment]
Hey @guyca thanks for the response... however, i updated to 2.0.2560 and even 2.0.2562 but its still happening.

What can I do?

**Comment by Tirex04** [comment]
@3210jr did you find the solution for this?
