### ISSUE TITLE
[v2] [iOS] 2.0.2475 was last version with working bottomTabs visible: false

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4112]
### Issue Description

Just made a test to check on which version `bottomTabs visible: false` stopped working.
So the last version it is workin on is 2.0.2475 and 2.0.2476 where it broke.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setDefaultOptions({
    bottomTabs: {
      visible: false,
      drawBehind: true,
      animate: false
    }
})
```

---
### Environment
* React Native Navigation version: 2.0.2577
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by yogevbd** [comment]
Fixed in version 2.0.2585

**Comment by rendomnet** [comment]
@yogevbd **NOT fixed** just checked and bottomTabs still visible.
