### ISSUE TITLE
[V2][iOS] topBar is not working correctly

### ISSUE THREAD

**Issue by pakyo-pan** [wix/react-native-navigation#4169]
### Steps to Reproduce / Code Snippets / Screenshots

1. If you set the property `background: transparent` to the topBar of screen-1:
```js
export default class Screen1 extends Component {
    static get options() {
        return {
            topBar: {
                title: {
                    text: 'transparent topBar'
                },
                drawBehind: true,
                background: {
                    color: 'transparent' // <-- if add this property
                }
            }
        };
    }
    ...
}
```
![image](https://user-images.githubusercontent.com/13342613/47222817-4815db00-d3ea-11e8-9ca6-477984be90a5.png)

2. Then push to screen-2, I set the `noBorder: true` on the topBar of screen 2, but it doesn't work.
```js
export default class Screen2 extends Component {
    static get options() {
        return {
            topBar: {
                noBorder: true // <-- This property does not work
            }
        };
    }
    ...
}
```
![image](https://user-images.githubusercontent.com/13342613/47223383-c161fd80-d3eb-11e8-8bd2-ba489faf1c49.png)

---
### Environment
* React Native Navigation version: 2.0.2598
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by yogevbd** [comment]
Fixed in 7dfec40722f255c21e805ab4bf5f2cc424e08266
version 2.0.2603

**Comment by pakyo-pan** [comment]
@yogevbd, It has not been fixed and still happens in version 2.0.2608

**Comment by pakyo-pan** [comment]
@yogevbd, It has not been fixed and still happens in version 2.0.2608

**Comment by pakyo-pan** [comment]
@yogevbd, It has not been fixed and still happens in version 2.0.2608

**Comment by pakyo-pan** [comment]
@yogevbd It has not been fixed, it still happens in version 2.0.2603 and 2.0.2608.

**Comment by yogevbd** [comment]
I can't reproduce.. can you post your code here or try to reproduce in our playground app?

**Comment by pribeh** [comment]
There's nothing too complicated about our base RNN setup. The following is what we're using:

```
	static options() {
		return {
			topBar: {
				noBorder: true,
				drawBehind: true,
				background: {
					color: 'transparent'
				}
			},
		};
	}
```

@yogevbd If you'd like I can give you access to our github repo too look at and debug.

**Comment by yogevbd** [comment]
@pribeh reach me on discord

**Comment by pakyo-pan** [comment]
@yogevbd I found the issue because I set `Navigation.setDefaultOptions({
        topBar: {
            background: {
                color: 'white'
            }
        }
    });`, now I removed this property.
```js
Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
        topBar: {
            background: {
                color: 'white'  // <-- if add this property
            }
        }
    });

    Navigation.setRoot({
         ...
    });
});
```
But I found a new issue. if you `pop` from Screen-2 and then `push` to the other screens, the other screens have no border

**Comment by pribeh** [comment]
@yogevbd I believe this issue is resolved. We can confirm by creating a background for the base screen that is different from a modal or overlapping screen. I believe the reason we could not confirm it is that we're unable to render anything underneath the topbar within the same screen (such as a flatlist). If we insert a flatlist into the screen with a transparent topbar the flatlist always renders below (NOT underneath) the topbar in the layout.

**Comment by guyca** [comment]
If `transparent` background is used, the screen has to be rendered behind the TopBar. Otherwise the transparency is meaningless. Seems like we can close the issue. Thanks @pribeh 👍

**Comment by pakyo-pan** [comment]
@guyca I still face this issue, why is it close ? I have set `drawBehind: true`.

**Comment by guyca** [comment]
@pakyo-pan Will be addressed in https://github.com/wix/react-native-navigation/issues/4218
