### ISSUE TITLE
Unable to get the example to work with react-native 0.37 and react-native-navigation 2.0.0-experimental.138

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#423]
### Issue Description

I have a mobile app in which I have been using `ex-navigator` to provide navigation and I am currently evaluating this library because it provides enhanced support for Android with the top tabs, overflow actions, drawers etc. I just created a new `react-native` app and copied over the example to it and performed the required changes. I am having multiple issue.

Issue 1
Problem on iOS
I have made one change to the example where I show a modal to begin with and then show a tab based application after five seconds because in my app also, I would want to show an authenticating modal to begin with and then show the app itself. So, basically the `app.js` file looks like this

```js
Navigation.showModal({
  screen: "example.ModalScreen", // unique ID registered with Navigation.registerScreen
  title: "Modal", // title of the screen as appears in the nav bar (optional)
  passProps: {}, // simple serializable object that will pass as props to the modal (optional)
  navigatorStyle: {}, // override the navigator style for the screen, see "Styling the navigator" below (optional)
  navigatorButtons: {}, // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
  animationType: 'slide-up' // 'none' / 'slide-up' , appear animation for the modal (optional, default 'slide-up')
})

setTimeout(() => {

// this will start our app
Platform.OS === 'ios' && Navigation.startTabBasedApp({
  tabs: createTabsForIos(),
  appStyle: {
    tabBarBackgroundColor: '#0f2362',
    tabBarButtonColor: '#ffffff',
    tabBarSelectedButtonColor: '#63d7cc'
  },
  drawer: {
    left: {
      screen: 'example.SideMenu'
    }
  }
});

Platform.OS === 'android' && Navigation.startSingleScreenApp({
 screen: {
   screen: 'example.FirstTabScreen',
   title: 'Navigation',
   navigatorStyle: {
     navBarBackgroundColor: '#4dbce9',
     navBarTextColor: '#ffff00',
     navBarSubtitleTextColor: '#ff0000',
     navBarButtonColor: '#ffffff',
     statusBarTextColorScheme: 'light'
   },
   topTabs: createTopTabsForAndroid()
 },
 drawer: {
   left: {
     screen: 'example.SideMenu'
   }
 }
});
}, 5000)
```
I am observing that the modal doesn't show up in iOS and the tab based application appears after 5 seconds as configured. Moreover, when I press on the `Show Modal Screen` link on the `FirstTabScreen`, I get the following error which has been reported in issue #357 as well.

```
Error: You attempted to set the key `onPress` with the value `"screenInstanceID5_events"` on an object that is meant to be immutable and has been frozen.
    at Error (native)
    at throwOnImmutableMutation (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13935:7)
    at _mergeScreenSpecificSettings (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84750:40)
    at Object.navigatorPush [as push] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84771:1)
    at Navigator.push (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:102572:27)
    at login$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:121266:2432)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29140:29)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29414:12)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29173:13)
    at next (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:118787:17)"
```

Issue 2
Problem on Android
After making the required changes for Android, nothing showed up on the simulator after I started the app. After some comparisons with the example, I found there there were some permissions missing in the AndroidManifest.xml file which were present in my application. So, I copied over the manifest file from the example and updated the package name etc. and started the app again, and this time the app showed up. I even saw the modal which is not seen in iOS as reported above. And the modal disappeared after 5 seconds and the android app showed up. But I made a couple of harmless changes which I even reverted, and the app stopped loading up again. I am not sure what is wrong because nothing shows up in the logcat. If I observe the logcat window in Android studio, it seems like when the app starts, there are some logs printed on the logcat and it just gets cleared away as soon as the app is loaded to the simulator and then I am not even able to reload the app because nothing happens when I press the Menu button. This error is kinda weird but its possible that someone else may have seen it as well. I see below error on Android at times in logcat

    11-09 18:02:16.829 27608-27608/com.testexnavigation W/unknown:React: Packager connection already open, nooping.

### Steps to Reproduce / Code Snippets / Screenshots

Create a new react-native app
Copy over the code in the example
Update the app.js as described above

---
### Environment
* React Native Navigation version: 2.0.0-experimental.138
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @varungupta85 
First off, .138 doesn't support RN 0.37. as you can see, we've already merged into master the branch where we upgraded RNN to support 0.37 - but it's not published to npm yet. I don't have an eta on when it will be published.

regarding your issue
I'm not sure how the native iOS is implemented, calling startApp should dismiss previous modals. Maybe there's a bug there. @gran33 Can you please look into this?

Regradless, I'm not sure how this is even worked on Android. A modal is a native dialog which requires an Activity. If you didn't call startApp - there's no activity and the modal can't be displayed.
The way I would tackle your use case is simply to call `startApp` twice. Once, with your authentication\Login screen. The second time after the user is authenticated, with your app's main screen.

**Comment by varungupta85** [comment]
hi @guyca thanks for the quick response. I had to change a couple of things to get it compile for Android. One change was in onActivityResult method where I needed to pass the activity and other was a compilation error related to not able to find symbol R. I copied the fixes for those two things from the master branch after which the code compiled successfully in Android Studio. I was definitely able to run the above mentioned code with the initial modal once. It's not working now though. I will remove the initial call to the `showModal` and try again.

**Comment by varungupta85** [comment]
I can confirm that once I remove the initial `showModal` call, the app started to work on Android. However, the iOS problem is still present. In the example app, if I click on the `Show Modal Screen` for the first time, it shows the modal screen. Then I close the modal by clicking `Close` in the navigation bar, `Close Modal` link in the modal screen or `Close All Modals` link in the modal screen and then I try to open the modal again, the app crashes and a red screen is shown with the following call stack.

```
Error: You attempted to set the key `onPress` with the value `"screenInstanceID5_events"` on an object that is meant to be immutable and has been frozen.
    at Error (native)
    at throwOnImmutableMutation (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13935:7)
    at _mergeScreenSpecificSettings (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84750:40)
    at Object.navigatorPush [as push] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84771:1)
    at Navigator.push (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:102572:27)
    at login$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:121266:2432)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29140:29)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29414:12)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29173:13)
    at next (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:118787:17)"
```

**Comment by guyca** [comment]
Hey @varungupta85 
0863bff91da920fbdcd25295f0ad590653c554c8 fixed the immutability crash.

Next week we will probably publish a version which will support RN 0.37

**Comment by varungupta85** [comment]
Great, thanks!. I will pick the commit and test it out. I am closing the issue. Will reopen if still have any problems.
