### ISSUE TITLE
[V3] Topbar with large title still shows small title

### ISSUE THREAD

**Issue by axpro** [wix/react-native-navigation#5454]
### Issue Description

When largeTitle is enabled the small title should be hidden and only shown on scroll. Right now they are both visible.

Other issues related to the largeScreen option:
- On first render the large title is scrolled up (hidden under the small title)
- If you scroll to view the large title and then push to another screen, that screen doesn't have a title. If you push without scrolling first, the pushed screen title is visible.

### Steps to Reproduce / Code Snippets / Screenshots

Add largeTitle to any screen (can be reproduced in playground):

```js
largeTitle: {
  visible: true
}
```

![Screenshot 2019-09-05 at 07 28 03](https://user-images.githubusercontent.com/1306629/64311975-dcf7d780-cfae-11e9-8126-a1a876b47f24.png)

Other issues:

![largeTitle](https://user-images.githubusercontent.com/1306629/64312585-4d075d00-cfb1-11e9-8f61-de445694fcab.gif)

---
### Environment
* React Native Navigation version: 3.1.2 (the issue didn't present itself on 3.0.0-alpha.2)
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone X - 12.2

**Comment by cesarm16** [comment]
same here

**Comment by carlitosspot** [comment]
yes, noticing the same issue as well. Has anyone tried a temp fix?

**Comment by djschilling** [comment]
I have the same issue, a fix would be greatly appreciated.

**Comment by nbolender** [comment]
+1

**Comment by ivan3177** [comment]
+1

**Comment by alexxgent** [comment]
Same. A dirty horrible workaround is to set the topbar title color the same as the topbar background color.

```
topBar: {
    largeTitle: { visible: true },
    background: {
      color: '#F7F7F7'
    },
    title: {
      color: '#F7F7F7'
    },
  },
```

**Comment by patrickschmelter** [comment]
Issue still persists on:

React Native Navigation version: 3.6.0 (last working is 3.1.0)
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 8 - 13.2.2

**Comment by djschilling** [comment]
Issue still exists

**Comment by patrickschmelter** [comment]
Still not stale

**Comment by djschilling** [comment]
still an issue

**Comment by nbolender** [comment]
Death to stalebot!

**Comment by joshfarrant** [comment]
Has anyone found a fix/workaround for this? Maybe something that could be applied through [patch-package](https://github.com/ds300/patch-package) 😄

**Comment by guyca** [comment]
This is fixed in 6.1.0

**Comment by jaredegan** [comment]
This is still happening to me.

React Native Navigation version: 6.3.0
React Native version: 0.61.5
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Debug. Both device & Sim. iPhone 11 Pro, iOS 13.3.1. iPhone 8 Simulator, iOS 13.3.

**Comment by jaredegan** [comment]
Here is a gif of the issue.
![large titles](https://user-images.githubusercontent.com/303795/76896017-7e69bb00-6867-11ea-8f9d-dc94a9edbba5.gif)

**Comment by jaredegan** [comment]
If I don't have a `ScrollView` as first view, then the large title shows up by default. However, since the full view isn't scrollable, it's locked to be large.

Here the component being returned:
```
return (
    <ScrollView>
      <Text>uhhh</Text>
      <Text>uhhh</Text>
      <Text>uhhh</Text>
</ScrollView>
```

**Comment by jaredegan** [comment]
Sorry for the rush of comments, but this workaround fixes the issue for me, should be a strong clue about what the real issue is. This is using `useNavigationComponentDidAppear` from `react-native-navigation-hooks`.

```jsx
const MyScreen: React.FC<MyScreenProps> = (props) => {

  const [didAppear, setDidAppear] = useState(false);

  useNavigationComponentDidAppear((didAppearEvent) => {
    setDidAppear(true);
  }, props.componentId);

  if (!didAppear) {
    return (<View />);
  }

  return (
    <ScrollView
      style={{
        width: '100%',
      }}
      contentContainerStyle={{
        alignItems: 'center',
        flex: 1,
      }}
    >
      <Text>My View Goes Here</Text>
    </ScrollView>
  );
};
```

**Comment by kanzitelli** [comment]
If anyone is still facing this issue, try out [these workarounds](https://gist.github.com/kanzitelli/76609c98dd39bea75f5451f286c412f2).
