### ISSUE TITLE
[v4]Null Pointer Exception at AHBottomNavigation.java after adding titles on the tabs from bottom navigation

### ISSUE THREAD

**Issue by stoica94** [wix/react-native-navigation#5928]
### Android Crashes after adding titles to the bottom tabs of navigation 

In the root of the stack we set titles to both tabs of the `bottomTabs`, and have `titleDisplayMode` set to `alwaysShow`. 

### Screenshots
![Screenshot 2020-02-15 at 16 38 58](https://user-images.githubusercontent.com/16940343/74589886-129af500-5012-11ea-8681-8f49a58ce64e.png)

```js                                                  
Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'BottomTabsId',
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    id: HOME_SCREEN,
                    name: HOME_SCREEN,
                    passProps: { ...config.props },
                    options: {
                      bottomTab: {
                        text: 'Home',
                        icon: require('res/images/navigation/home-outline-new.png'),
                        selectedIcon: require('res/images/navigation/home-filled-new.png'),
                        iconInsets: { top: 0, bottom: 0 },
                        iconColor: color[colorScheme].textSecondary,
                        selectedIconColor: color.primary,
                        textColor: color[colorScheme].textSecondary,
                        selectedTextColor: color.primary,
                        fontSize: 11,
                        selectedFontSize: 11,
                        animate: false,
                      },
                      bottomTabs: {
                        backgroundColor: color[colorScheme].top,
                        titleDisplayMode: 'alwaysShow',
                        animate: false,
                      },
                      statusBar: {
                        style: colorScheme === 'dark' ? 'light' : 'dark',
                        backgroundColor: color[colorScheme].top,
                      },
                    },
                  },
                },
              ],
            },
          },
          {
            stack: {
              children: [
                {
                  component: {
                    id: PROFILE_SCREEN,
                    name: PROFILE_SCREEN,
                    options: {
                      bottomTab: {
                        text: 'Tab',
                        icon: require('res/images/navigation/profile-icon-outlined-new.png'),
                        selectedIcon: require('res/images/navigation/profile-icon-filled-new.png'),
                        iconInsets: { top: 0, bottom: 0 },
                        iconColor: color[colorScheme].textSecondary,
                        selectedIconColor: color.primary,
                        textColor: color[colorScheme].textSecondary,
                        fontSize: 11,
                        selectedFontSize: 11,
                        animate: false,
                      },
                      bottomTabs: {
                        backgroundColor: color[colorScheme].top,
                        titleDisplayMode: 'alwaysShow',
                        animate: false,
                      },
                      statusBar: {
                        style: colorScheme === 'dark' ? 'light' : 'dark',
                        backgroundColor: color[colorScheme].top,
                      },
                    },
                  },
                },
              ],
            },
          },
        ],
      },
    },
  });
```

From some logs I think the crash happens when we push another screen onto the stack that has bottom tabs hidden: 

```js 
Navigation.push(componentId, {
    component: {
      name: NEW_SCREEN,
      passProps: { ...config.props },
      animations: { ...config.animations },
      options: {
         bottomTabs: {
          visible: false,
          drawBehind: true,
          titleDisplayMode: 'alwaysHide',
        },
      },
    },
  });
```

Another note on this is that this crash didn't happen before we put `titleDisplayMode` to `alwaysShow` on bottomTabs on the root stack because at that time we didn't have titles on the bottom tabs, but after this setting this crash started to appear. 

We tried to update RNN, but that didn't help. We went from 3.x.x up to 4.6.2. 

### Reproduce
* Unfortunately we cannot reproduce this issue. We only get reports of it from releases
---
### Environment
* React Native Navigation version: 4.6.2
* React Native version: 0.61.2
* Platform: Android
* Device info: Android in Release
![Screenshot 2020-02-15 at 16 57 23](https://user-images.githubusercontent.com/16940343/74590137-5a228080-5014-11ea-94ff-3cf5a0d98efb.png)

Please tell me what other information could be useful for solving this issue

**Comment by stoica94** [comment]
This problem still occurs

**Comment by guyca** [comment]
hmmm can you reproduce this in the playground app? I think this is resolved in a recent version.

**Comment by stoica94** [comment]
We are currently on version 5.1.1 but this issue still occurs in production. What version do you recommend?

**Comment by stoica94** [comment]
Another update on this. I got the sentry report for this crash. It happens on 
`Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference`

Call stack: 
```
com.aurelhubert.ahbottomnavigation.a in b at line 16
com.reactnativenavigation.d.a in a at line 118
com.reactnativenavigation.d.a in lambda$CU7TWa_vc29dFWXjO_gWOWIo16k
com.reactnativenavigation.d.-$$Lambda$a$CU7TWa_vc29dFWXjO_gWOWIo16k in run at line 4
com.reactnativenavigation.e.l in a at line 4
com.reactnativenavigation.d.a in a at line 7
com.reactnativenavigation.f.a.e in b at line 25
com.reactnativenavigation.f.l in b at line 5
com.reactnativenavigation.f.a in b
com.reactnativenavigation.f.l in onGlobalLayout at line 33
android.view.ViewTreeObserver in dispatchOnGlobalLayout at line 945
android.view.ViewRootImpl in performTraversals at line 2351
android.view.ViewRootImpl in doTraversal at line 1465
android.view.ViewRootImpl$TraversalRunnable in run at line 7233
android.view.Choreographer$CallbackRecord in run at line 979
android.view.Choreographer in doCallbacks at line 791
android.view.Choreographer in doFrame at line 726
android.view.Choreographer$FrameDisplayEventReceiver in run at line 965
android.os.Handler in handleCallback at line 790
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loop at line 164
android.app.ActivityThread in main at line 6651
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 438
com.android.internal.os.ZygoteInit in main at line 810
```

**Comment by pi-xel** [comment]
I've experienced the same issue. If I recollect correctly, it happens when you set selectedFontSize for a component with bottomtabs, push another component with selectedFontSize not set and then dismiss a modal shown on top of the second component.

Solution seems to be to remove selectedFontSize from the first component or to add selectedFontSize to all components.
