### ISSUE TITLE
[v6][ios] White topBar background on navigating back

### ISSUE THREAD

**Issue by deanhet** [wix/react-native-navigation#6055]
### Issue Description
I've just updated our app to use the latest React-Native Navigation. I now seem to be getting a new issue on iOS where if I navigate backwards in the app, the header blanks to a white background.

I've had a look through the changelog and there's nothing I can spot that would make this new behaviour.

![Mar-18-2020 13-41-41](https://user-images.githubusercontent.com/1846510/76966831-74ef5a00-691e-11ea-8901-81f38e14d3df.gif)

Is there an option I'm missing or is this a bug? 

Current defaultOptions:
```js    
  Navigation.setDefaultOptions({
    layout:                {
      orientation:              ['portrait'],
      backgroundColor:          Colors.background,
      componentBackgroundColor: Colors.background
    },

    modalPresentationStyle: 'pageSheet',

    bottomTabs: {
      titleDisplayMode: 'alwaysShow',
      backgroundColor:  '#1C2432',
      hideShadow:       false,
      elevation:        15
    },

    bottomTab: {
      textColor:         '#4b747c',
      selectedTextColor: Colors.accentBright,
      fontSize:          8,
      fontFamily:        'Nunito-Regular'
    },

    topBar: {
      title:      {
        fontFamily: 'Nunito-Bold',
        fontSize:   18,
        color:      '#fff'
      },
      backButton: {
        icon:      require('../assets/images/arrowBack.png'),
        color:     '#fff',
        showTitle: false
      },
      buttonColor: {
        color: '#fff'
      },
      background: {
        color: Colors.background
      }
    },

    statusBar: {
      backgroundColor: Colors.background2,
      style:           'light'
    }
```
---
### Environment
* React Native Navigation version: 6.3.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X, 13.3, Debug

**Comment by yogevbd** [comment]
Couldn't reproduce it on the playground app. Can you please reproduce it there?

**Comment by geroale** [comment]
Same issue here. I am using only defaultOptions too.

**Comment by deanhet** [comment]
Thanks for taking a look! I'll take a look at reproducing this in the playground at some point during this week. 👍🏻

**Comment by yogevbd** [comment]
Managed to reproduce it on a pure native iOS app. It looks like this is a bug on iOS 13 and not in rnn itself.
https://stackoverflow.com/questions/60799209/white-flash-when-popping-using-pop-gesture-on-ios-13

Next step will be to try and reproduce it on xcode-beta with the latest iOS. If it's not fixed there I will file a bug report with Apple.

**Comment by yogevbd** [comment]
Managed to reproduce it in the playground app and it's a different issue than the one I described above.
When current screen in stack hides the `topBar` and the next screen present the `topBar`,  there's a need to set `topBar.animate: true` in the options of the screen that hides the `topBar`.

```js
static options() {
  return {
    topBar: {
      visible: false,
      animate: true
    }
  };
}
```

**Comment by geroale** [comment]
@yogevbd Thank you for the quick response. Unfortunately, this solution doesn't work in my case, probably because I'm not hiding the topBar from the screen's options but the stack's options. I tried to put the `animate` property everywhere (in the stack + each screen option) but it's not working. Also, I would like to confirm that this problem came with v6 and the v5 was working fine, as reported in the title. (I am using that in production now)

**Comment by deanhet** [comment]
Unfortunately, can confirm much as the same above, setting animate didn't really solve anything.

**Comment by yogevbd** [comment]
@geroale your example helped me to reproduce it in the playground app, fixed in this PR: #6069, but still it doesn't seems the exact same issue this ticket is about.

**Comment by VEnom42** [comment]
I had the same issue. Setting `animate: true` on both screens fixed it. But on iOS 12.4 still get white background. With background color on hidden topbar it works good on all iOS versions:
```js
static options() {
  return {
    topBar: {
      visible: false,
      animate: true
      background: {
        color: topBarDefaultColor,
      },
    }
  };
}
```
My rnn version is 6.9.1.
