### ISSUE TITLE
[ios] React Native Navigation App won't load for iOS 13.4

### ISSUE THREAD

**Issue by anirudh-mehta-dap** [wix/react-native-navigation#6100]
My Mac just upgraded to MacOS Catalina 10.15.4 and it updated my Xcode to 13.4 (not sure if this caused the issue but perhaps it's relevant)

I installed a fresh copy of React Native App with react-native init and installed RNN 6.4.0 but my app won't load. I tried the manual steps mentioned in the documentation using CocoaPods and Native Install but it just won't go beyond the loading screen. 

Here is what my screen looks like:

![image](https://user-images.githubusercontent.com/11057721/78303435-8a769d80-7534-11ea-8b5a-c521a830902b.png)

### Steps to Reproduce / Code Snippets / Screenshots

1. Install a new app using react-native init
2. Install RNN using npm
3. Link the app
4. pod install
5. Run the app using npx react-native run-ios
6. Replace the inde.js with

```js                                                         
import { Navigation } from "react-native-navigation";
import App from "./App";
Navigation.registerComponent('com.myApp.WelcomeScreen', () => App);
Navigation.events().registerAppLaunchedListener(() => {
   Navigation.setRoot({
     root: {
       stack: {
         component: {
           name: 'com.myApp.WelcomeScreen'
         }
       }
     }
  });
});
 ```                                                          

---
### Environment
* React Native Navigation version: ^6.4.0
* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/ iPhone 11 iOS 13.4

**Comment by markmoomoo** [comment]
I had this black screen somewhere else before.
did you try to solve this by:
[https://github.com/wix/react-native-navigation/issues/4580#issuecomment-482669978]

**Comment by anirudh-mehta-dap** [comment]
@markmoomoo No it didn't work. I have decided to move away from React Native Navigation to React Navigation. The reason for using React Native is for faster prototyping and fast to market but I found myself spending more time debugging this library which almost never works with the latest RN or iOS version. I would rather take some performance cut than lose time on debugging but thank you for your help.

**Comment by samithaf** [comment]
Could be unrelated but we noticed a similar issue with our end user monitoring software that some users were having black screen issue in certain version of OS in iPad. 
The way we solved this problem was change the way we have implemented the splash screen. We changed to the implementation to use storyboard.  E.g. how to do https://medium.com/flawless-app-stories/change-splash-screen-in-ios-app-for-dummies-the-better-way-e385327219e

**Comment by garydevenay** [comment]
I am currently experiencing this issue, though only when building in release mode (iOS) on a physical device. I have also tried the suggestion in #4580 but it doesn't solve the issue.

The launch screen will display and then everything goes black. This doesn't happen when building in debug mode on the Xcode simulator.

**Comment by TimonSotiropoulos** [comment]
@guyca this issue is still happening. Has anyone come up with a solution for this?

**Comment by eladgel** [comment]
@garydevenay @TimonSotiropoulos from my experience it is related to a missing launch image:
go to RNNSplashScreen.m and put a breakpoint there. Debug it on a working example then a non working example and you will find the delta, and probably the missing resolution.

**Comment by dooleyb1** [comment]
> I am currently experiencing this issue, though only when building in release mode (iOS) on a physical device. I have also tried the suggestion in #4580 but it doesn't solve the issue.
> 
> The launch screen will display and then everything goes black. This doesn't happen when building in debug mode on the Xcode simulator.

Currently experiencing this exact issue, did you manage to get around it?
