### ISSUE TITLE
not hidding bottomTabs after navigate to child

### ISSUE THREAD

**Issue by webforuse** [wix/react-native-navigation#6282]
### Issue Description

1. Set default options
bottomTabs: {
      animate: true,
      drawBehind: false,
      visible: false,
    },

2. Create root bottom tabs screen
bottomTabs: {
          visible: true,
          animate: true,
          drawBehind: true,
          currentTabIndex: 0,
          titleDisplayMode: 'alwaysShow',
        },

3. Navigate to child screen (with settings)
bottomTabs: {
          visible: false,
          animate: true,
          drawBehind: true,
        },

Result: bottom tabs not hidding (working on 6.4 and 6.5)

---
### Environment
* React Native Navigation version: 0.62.2
* React Native version: 6.7.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by guyca** [comment]
I believe this is fixed in 6.7.2

**Comment by webforuse** [comment]
what evidence should I give ?

**Comment by wsliaw** [comment]
similar to this #6268 
still happening on `6.7.2` & `6.7.2-snapshot.1024`

**Comment by N3TC4T** [comment]
@guyca 

The bottomTabs will be appear after second push

`Root -> Push (hidden) -> Push (shown)`

btw removing this line fixed the issue for me

https://github.com/wix/react-native-navigation/commit/4e1ac713944373d8d2c5b251912e1a872b2d00a7#diff-4831fe162852482032e0b1e9bf5b9f37R20

**Comment by guyca** [comment]
@wsliaw @N3TC4T @webforuse Please fork the library and push a reproduction. I wasn't able to reproduce any issue following the steps described in the issue.

**Comment by webforuse** [comment]
not fixed

**Comment by markmoomoo** [comment]
6.9.1 still not fixed? @webforuse I got the problem too, looks like not fixed yet

**Comment by webforuse** [comment]
Not fixed
