### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by vimalswaroopj** [wix/react-native-navigation#7433]
I am using react native navigation library in react native, the keyboard in android is pushing the UI up. If I remove some of the options such as:`navigationBar: {
        visible: false,
      },`
it works fine, but not all the time it works fine.

Can anyone give some hints or tips to solve this issue. 

We are using "KeyboardAwareScrollView" to make the keyboard scroll the view to bring the input filed on top of keyboard.

**Comment by ItsNoHax** [comment]
If you check your AndroidManifest, what `android:windowSoftInputMode` are you using?

**Comment by vimalswaroopj** [comment]
> If you check your AndroidManifest, what `android:windowSoftInputMode` are you using?

android:windowSoftInputMode="adjustPan"
tried "adjustResize" as well but the issue is still there

**Comment by keeprock** [comment]
I got the same issue. It starts with 7.24.0. 7.24.1 doesn’t' fix it either. The latest release (7.25.1) still contains it.

Bug looks like this:

WIthout keyboard:
![image](https://user-images.githubusercontent.com/5209820/152118518-2a49bf60-6475-41fe-84d8-3ccfa45a51db.png)

With keyboard:
![image](https://user-images.githubusercontent.com/5209820/152118530-639eb2b1-e8c2-42ba-be40-e1c9feb01ccc.png)

Notice a light brown block under the white background, while the keyboard is up. It shouldn't be there.

For me, the solution is to downgrade to the previous version (7.23.1). 

![image](https://user-images.githubusercontent.com/5209820/152121097-31b72580-81d2-4c1a-8569-07742df66031.png)

**Comment by swabbass** [comment]
Hey, [vimalswaroopj](https://github.com/vimalswaroopj), can you please share a reproducible demo, a minimal one, so we can debug what is really happens in your code? can you, kindly, follow the issue guidelines so we have all the information about how to reproduce your issue? :]

**Comment by swabbass** [comment]
Should be fixed [here](https://github.com/wix/react-native-navigation/pull/7441).

**Comment by Mitesh-2009** [comment]
I am also having this type of issue, in android 8

**Comment by vimalswaroopj** [comment]
Hi @swabbass, I am still getting this issue even after the changes. I have shared a reproducible demo.
https://user-images.githubusercontent.com/42696640/153193258-968072e5-1fd5-46f2-944e-7f5e5cb27e29.mov

**Comment by vimalswaroopj** [comment]
Hi @swabbass, I am still getting this issue even after the changes in react native navigation version 7.25.2. I have shared a reproducible demo.

https://user-images.githubusercontent.com/42696640/153193923-8f1de8d4-ffbb-47cd-8e05-48498a4fb5c3.mov
