### ISSUE TITLE
Can not push a screen after dismiss an overlay

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#7546]
## 🐛 Bug Report

Can not push a screen after dismiss an overlay

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Show an overlay using below code:
Navigation.showOverlay({
    component: {
      name: modalName,
      options: {
        overlay: {
          interceptTouchOutside: true,
          handleKeyboardEvents: true,
        },
        layout: {
          componentBackgroundColor: COLORS.transparent,
        },
      },
      passProps,
    },
  });
2. Dismiss overlay
3. Push to a screen using Navigation.push(componentId, {.....})
4. It shows Running "Profile" with {"rootTag":661,"initialProps":{"componentId":"Component14"}} but not push to this screen on the UI as my expectation.

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: 7.28.0
- React Native version: 0.68.2
- Platform(s) (iOS, Android, or both?): both ios and android
- Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)
<img width="641" alt="Screen Shot 2022-06-22 at 00 14 38" src="https://user-images.githubusercontent.com/28852565/174859329-30ef5850-a96f-4174-a035-ebf81005cfcb.png">

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by suupham2506** [comment]
> 
I use react native modalize.
You can see example here. https://github.com/jeremybarbet/react-native-modalize/tree/master/examples/react-native-navigation

Not sure the bug from react native modalize or react native navigation, but hopefully you can help me investigate and solve this issue.

**Comment by suupham2506** [comment]
hey @Andarius, do you think this issue should be solved by react-native navigation?

**Comment by ludwig-pro** [comment]
when you display a overlay, the componentId change but when you dismiss it, you don't have a new componentId

```
 Navigation.events().registerComponentDidAppearListener((event) => {
    console.log('currentComponentId', event.componentId);
    }
```

**Comment by sam-houle1** [comment]
This is definitely a react-native navigation issue, I don't use modalize and still have this issue. @Andarius is it ever going to be fixed ?

**Comment by eros-piccioni** [comment]
I have the samedescribed issue with react-native-navigation 7.29.0 and react-native 0.70.8

**Comment by thiennd99** [comment]
i have had also this issue with react-native-navigation 7.7.0. Is this bug going to be fixed ?

**Comment by kevin-madden-gf** [comment]
I am also experiencing this issue, react-native-navigation 7.32.2, react native 0.71

**Comment by filipef101** [comment]
Did experience something similar, what might be causing this is trying to show the overlay more than once, possibly with same id. so I keep a variable to track if it's shown or not. only show if not visible, on unmount set it to false
