### ISSUE TITLE
The title get's truncated/trimmed for some reason.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#764]
Hey there.. Any idea why the nav bar title is truncated/trimmed on some screens but not  others?

Here I got the word `Client` (6 characters). If I type `Clien` (5 character it shows) but if it's 6 characters it get's trimmed (shows `...` at the end).

On other screens I had success using 15 character words with no problem at all.

<img width="616" alt="screen shot 2017-02-14 at 21 54 10" src="https://cloud.githubusercontent.com/assets/3070948/22946775/1a30ad12-f301-11e6-8f5d-b4f6e9015a36.png">

Also if I add a space before the word `Client` or if I type a second word like `Client Name` the problem goes away and I get the full title..

Any ideas?
thanks

**Comment by perrosnk** [comment]
@SudoPlz this bug should have been fixed in RN0.38. Please have a look at #337

**Comment by SudoPlz** [comment]
Well I'm on RN0.39.2 and I still get it.
When I get to my office I'll let you know what rnn version I'm at.

**Comment by perrosnk** [comment]
@guyca  I noticed that this bug appears on iphone 6 simulator, and iphone 6 device. But not on iphone 5 simulator, so might have to do with the resolution @SudoPlz Can you please confirm in which device are you experiencing this bug?

**Comment by flavordaaave** [comment]
I got the same problem, but only with the subtitle.

If the subtitle is shorter than the title, the subtitle is truncated:
![simulator screen shot 22 03 2017 11 22 35](https://cloud.githubusercontent.com/assets/5305150/24193424/7d5208de-0ef2-11e7-8b06-ff93a86b33a1.png)

But if the title is longer, the subtitle is NOT truncated anymore:
![simulator screen shot 22 03 2017 11 23 29](https://cloud.githubusercontent.com/assets/5305150/24193446/8dc68870-0ef2-11e7-8049-b1b5c5243068.png)

So it seems the subtitle is always just as wide as the title is...

Furthermore the subtitle does not properly fit into the header (see small "g" letter in subtitle beeing cut off)

**Comment by grin** [comment]
@flavordaaave I fixed the subtitle issue in https://github.com/wix/react-native-navigation/pull/928

**Comment by grin** [comment]
@flavordaaave btw, you can set the subtitle font size through the `navBarSubtitleFontSize` property in `navigatorStyle`

**Comment by perrosnk** [comment]
@grin does this solve title's issue as well?

**Comment by grin** [comment]
@perrosnk I never run into the issue with title...but you could try the same technique and add `[titleLabel sizeToFit];` to here: https://github.com/wix/react-native-navigation/blob/master/ios/Helpers/RCCTitleViewHelper.m#L200

**Comment by SCadilhac** [comment]
Hi @grin I confirm `sizeToFit` is needed on `titleLabel` too. Without it, it's the title which is limited to the subtitle's width. Would you like to push this to the maintsteam?

**Comment by JohnProg** [comment]
any update? I have the same problem.

**Comment by mkuczera** [comment]
@JohnProg which version are you currently using? Should be resolved since [f6d2c33](https://github.com/wix/react-native-navigation/commit/f6d2c334c3defc6bf0851b4182b5bfd860b470eb)

**Comment by guyca** [comment]
Closing as this issue is fixed, as @mkuczera mentioned.

**Comment by 404sand808s** [comment]
I seem to be getting this on RN 0.54 and react-navigation 1.5.8. The word Insurance is being truncated to Insuran...

Interestingly, if I add an "s" to make Insurances, it no longer gets truncated. Go figure.
