### ISSUE TITLE
RNN on RN 0.71.1 is not linked/launched correctly in AppDelegate

### ISSUE THREAD

**Issue by pid0r-3blan** [wix/react-native-navigation#7676]
### What happened?

RNN `7.31.1` doesn't work with the RN app initialized using `npx react-native init` with the latest version of RN currently available (`0.71.1`). It shows `Invariant Violation` error on start:
```
Invariant Violation: "MyApp" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

This is probably because `AppDelegate.mm` [file template](https://github.com/facebook/react-native/blob/main/template/ios/HelloWorld/AppDelegate.mm#L7) was changed from what we had in [react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript/blob/2c68dc2d87f988035c6c89a790ddc9136eb991b7/template/ios/HelloWorld/AppDelegate.mm#L32). It's because AppDelegate now [should inherit](https://reactnative.dev/docs/new-architecture-app-intro#ios---make-your-appdelegate-conform-to-rctappdelegate) from `RCTAppDelegate`. Now there's no `bridge` initialisation there (it happens in the parent `RCTAppDelegate` class method). And the link stage doesn't add anything to the file except `extraModulesForBridge`:
```Objective-C++
#import "AppDelegate.h"
#import <ReactNativeNavigation/ReactNativeNavigation.h>

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"MyApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end
```

p.s. I'm experienced RNN user, the last time I used it was with RN `0.70.6` initialized with `react-native-template-typescript` tempalte and RNN `7.30.6` and everything worked correctly.

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

I created the app using `npx react-native init`. RN version is `0.71.1`. Then I did `yarn add react-native-navigation`, `npx rnn-link` and `cd ios && bundle exec pod install`, it was linked and installed correctly (there wasn't any errors).

Then updated root `index.js` file:
```TSX
import { Navigation } from "react-native-navigation";
import App from "./App";

Navigation.registerComponent('MyApp.WelcomeScreen', () => App);
Navigation.events().registerAppLaunchedListener(() => {
   Navigation.setRoot({
     root: {
       stack: {
         children: [
           {
             component: {
               name: 'MyApp.WelcomeScreen'
             }
           }
         ]
       }
     }
  });
});
```

### In what environment did this happen?

React Native Navigation version: 7.31.1
React Native version: 0.71.1
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16
Device model: Xcode Simulator Version 14.1 (986.5)
iOS version: 16.1

**Comment by pid0r-3blan** [comment]
I think it's not that hard to resolve this, just rewrote this method in app delegate https://github.com/facebook/react-native/blob/b314e6f147fdfcd71e7ba3b17338bb44356df98e/Libraries/AppDelegate/RCTAppDelegate.mm#L33 . But it worth to mention in docs, I can submit PR.

Resulting `AppDelegate.mm` is:
```Objective-C++
#import "AppDelegate.h"
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import <React/RCTAppSetupUtils.h>

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"MyApp";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  BOOL enableTM = NO;
#if RCT_NEW_ARCH_ENABLED
  enableTM = self.turboModuleEnabled;
#endif

  RCTAppSetupPrepareApp(application, enableTM);

  if (!self.bridge) {
    self.bridge = [self createBridgeWithDelegate:self launchOptions:launchOptions];
  }
  [ReactNativeNavigation bootstrapWithBridge:self.bridge];
#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  self.bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:self.bridge
                                                               contextContainer:_contextContainer];
  self.bridge.surfacePresenter = self.bridgeAdapter.surfacePresenter;
#endif

  return YES;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feature is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  return true;
}

@end
```

**Comment by moonjava2005** [comment]
I have tried with this solution but it seem not working. It got crash right after start

**Comment by Garamani** [comment]
@pid0r-3blan Thank you so much 🙏

After a week of trying I could finally make the React Native Navigation work inside RN 0.71.4

Important notes:

- Remember to add: `#import <React/RCTAppSetupUtils.h>`

- Remember to replace this line `return [super application:application didFinishLaunchingWithOptions:launchOptions];`
  with this line: `return YES;`
**Possible Error:** _Invariant Violation: "MyAppName" has not been registered._

- Remember to delete these lines: 
`[ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions]`
`RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions]`
`[ReactNativeNavigation bootstrapWithBridge:bridge]`
**Possible Error:** _Exception 'Bridge not yet loaded! Send commands after Navigation.events().onAppLaunched()_

**Comment by ksarna** [comment]
This should go straight to docs 🙏

**Comment by yogevbd** [comment]
Fixed in #7733

**Comment by vcellucci** [comment]
I still can't get it to work.  I tried all suggestions here.  It either crashes, black screen, or I get an error that the app was not registered.

**Comment by topi-identio** [comment]
My app was getting stuck in splash screen, and it seems like my issue was that I was missing these lines:
```
if (!self.bridge) {
    self.bridge = [self createBridgeWithDelegate:self launchOptions:launchOptions];
}
```
